### ISSUE TITLE
is that possbile to make it as GZ ?

### ISSUE THREAD

**Issue by simonchen007** [lbernstone/miniz-esp32#1]
hello,

is that possbile to make it as gz, and sent it out to the browser  ?

**Comment by lbernstone** [comment]
See https://github.com/tobozo/ESP32-targz/blob/master/examples/ESP32/Update_from_gz_stream/Update_from_gz_stream.ino.  If you are trying to compress more than ~10KB, you likely will want to use PSRAM instead.

**Comment by simonchen007** [comment]
thanks
